version: '2'
services:
  shopee-farm-help:
    build: .
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./src:/home/dormnet/src
    networks:
      - proxy
    expose:
      - "3000"

networks:
   proxy:
     external:
       name: dog_proxy